import type {
    GetServerSideProps,
    GetServerSidePropsContext,
    NextPage,
} from 'next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import Head from 'next/head'
import { Word } from 'osdpjs/lib/word'
import { WordInfo } from '../components/word-info'
import { WordSearch } from '../components/word-search'
import { SearchWord } from '../services/languages'
import styles from '../styles/home.module.css'

export const getServerSideProps: GetServerSideProps = async (
    context: GetServerSidePropsContext
) => {
    let { dict, word, type, search } = context.query
    const { locale } = context
    if (!word) {
        word = ''
    }
    if (!type) {
        type = 'verb'
    }
    if (!search) {
        search = 'false'
    }
    if (!dict) {
        dict = 'cy'
    }
    const wordResult = await SearchWord(
        dict as string,
        search as string,
        word as string,
        type as string
    )

    return {
        props: {
            wordToSearch: word,
            type: type,
            search: search,
            result: wordResult,
            ...(await serverSideTranslations(locale as string, [
                'common',
                'home',
            ])),
        },
    }
}

interface HomeProps {
    wordToSearch: string
    type: string
    search: string
    result: Word
}

const Home: NextPage<HomeProps> = ({ wordToSearch, type, search, result }) => {
    if (result) {
        type = result.type
        wordToSearch = result.normalForm
    }
    return (
        <>
            <WordSearch
                initialSearchSelect={search}
                initialWordToSearch={wordToSearch}
                initialWordType={type}
                result={result}
            />
            <div className={styles.container}>
                <Head>
                    <title>Open Celtic Dictionary; Digi Web-Interface</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/digi_v2.png" />
                </Head>
                <WordInfo word={result} />
            </div>
        </>
    )
}

export default Home
