import type { NextPage } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Open Celtic Dictionary; Digi Web-Interface</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/digi_v2.png" />
      </Head>
    </div>
  );
};

interface serverSideProps {
  locale: string
}

export const getStaticProps = async (params: { locale: string; }) => {
  return {
    props: {
      ...(await serverSideTranslations(params.locale, ["common", "home"])),
    },
  };
};

export default Home;
